//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test_MVC.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Address
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_Address()
        {
            this.tb_Employee = new HashSet<tb_Employee>();
        }
    
        public int ID { get; set; }
        public string City { get; set; }
        public byte[] State { get; set; }
        public byte[] Pinode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Employee> tb_Employee { get; set; }
    }
}
